name: Run linter and unit tests

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm install --no-package-lock --no-fund

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test
