name: Run JSHint

on: [push]

jobs:
  jshint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install --no-package-lock jshint
      - name: Run JSHint
        run: jshint .
