name: Zizmor audit

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/zizmor.yml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/zizmor.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  zizmor:
    name: Run zizmor auditor
    runs-on: ubuntu-22.04
    permissions:
      security-events: write # Required so zizmor-action can upload SARIF findings to code scanning.
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          persona: auditor
